### PR TITLE
Use less shared memory

### PR DESCRIPTION
**Pull request by JeromeMartinez**

### CODE REVIEW

**Comment by kieranjol** [comment]
Hi Jerome, I can't compile on windows ATM so if this is different to the
binary you shared before, I can only test on UNIX..

**Comment by JeromeMartinez** [comment]
The principle has not changed since the previous binary, so I think there is no need to test before the merge and it will be in the [snapshots](https://mediaarea.net/download/snapshots/binary/rawcooked/) tomorrow.

**Comment by kieranjol** [comment]
Awesome!

**Comment by retokromer** [comment]
Works fine on my end. Thank you!

**Pull request merged**
