### PR TITLE
Add project files for chocolatey package

### PR DESCRIPTION
**Pull request by g-maxime**
Signed-off-by: Maxime Gervais <gervais.maxime@gmail.com>

### CODE REVIEW

**Comment by retokromer** [comment]
Good to see Chocolatey supported!

**Comment by JeromeMartinez** [comment]
Pending https://chocolatey.org/packages/rawcooked

**Comment by JeromeMartinez** [comment]
Package is accepted by Chocolatey.

**Comment by retokromer** [comment]
>Package is accepted by Chocolatey.

Wonderful!

**Pull request merged**
