### PR TITLE
Files listing is not always sorted, we sort it for sequence detection

### PR DESCRIPTION
**Pull request by JeromeMartinez**

### CODE REVIEW

**Comment by JeromeMartinez** [comment]
pre-sorting by the OS depends a lot of the OS (and version), thanks @pjotrek-b for the report.

**Comment by pjotrek-b** [comment]
Thanks for finding the reason so quickly :smile:

**Comment by JeromeMartinez** [comment]
@pjotrek-b please test [corresponding build](https://mediaarea.net/download/snapshots/binary/rawcooked/20180607-2/).

**Comment by pjotrek-b** [comment]
Tested with build **18.06.20180607**:
Encoding now works as expected: no more multiple video streams in the output, no more crash, proper runtime :smile:

**Comment by retokromer** [comment]
We’ve played on [various settings](https://reto.ch/training/2018/20180608.html) and for what we’ve tested all worked fine. Hooray!

**Comment by JeromeMartinez** [comment]
@retokromer if there are comments, please [fill issues](https://github.com/MediaArea/RAWcooked/issues) so we can track them well.

**Comment by retokromer** [comment]
BTW: Also the installation via Linuxbrew did work. (Merci @g-maxime!)

**Pull request merged**
