### PR TITLE
add man page

### PR DESCRIPTION
**Pull request by retokromer**

### CODE REVIEW

**Comment by JeromeMartinez** [comment]
The Travis fail is not due to this PR, we check

**Comment by retokromer** [comment]
Caveat: I don’t know if this is the correct place on the site structure.

I can update the man when options etc. are implemented.

**Comment by retokromer** [comment]
Please do not merge this one now. I’ll very soon update according to the discussion with @JeromeMartinez.

**Comment by retokromer** [comment]
@JeromeMartinez Please comment.

**Comment by JeromeMartinez** [comment]
Good enough for a first version, I merge it hen I'll see to clean it up if needed or request an update.
@g-maxime please add the man page in the Linux releases (also for macOS?)

**Comment by retokromer** [comment]
On macOS the man works the same way than in Linux.

**Pull request merged**
