### PR TITLE
update help prompt

### PR DESCRIPTION
**Pull request by retokromer**
- simplify
- add `-v` to `--version` option

### CODE REVIEW

**Comment by JeromeMartinez** [comment]
My idea with "directory" in help is to prioritize the use of directories in the command line.
Using file names is more for less classic usage.

**Comment by retokromer** [comment]
To me they are at the same logical level, and it’s confusing to discriminate them here, but possibly it’s just me?

**Comment by JeromeMartinez** [comment]
Reading again the change suggestion and comment, it is maybe me.
Maybe the change is ok, I would be in favor to add a line saying that directory is preferred in order to take all files and for making the mjv file with directory name (ho, I'll add an option for setting the mkv file name).

**Comment by retokromer** [comment]
I‘ve dropped the short version of… version.

**Comment by retokromer** [comment]
I’ve added the message.

**Pull request merged**
