### PR TITLE
Freeze FFmpeg version

### PR DESCRIPTION
**Pull request by JeromeMartinez**
Right now FFmpeg Git has some compilation issues (at least with our ./configure settings)

### CODE REVIEW

**Comment by retokromer** [comment]
In my experience, it‘s always better to include the last FFmpeg release in each of our releases, because the HEAD has much more often issues than the releases.

**Comment by JeromeMartinez** [comment]
In RAWcooked? We don't provide FFmpeg, users have to install it (so they choose the version they want).
Here, this is only for Travis (HEAD us useful mostly when they accept a patch used by RAWcooked).

**Comment by JeromeMartinez** [comment]
(a good example is that the latest stable release has no support of 12-bit alpha, I need to use something else)

**Comment by retokromer** [comment]
In my opinion, we have to guide the users to a correct installation, if we wish that RAWcooked is adopted outside the geek community.

(When I have this kind of issue, the last release with the corresponding patch works very fine on my side. Usually I simply do integrate the patch into the corresponding Homebrew/Linuxbrew formula, because it’s the «only» distribution we do provide. I know that for you it’s more complex…)

**Comment by JeromeMartinez** [comment]
> In my opinion, we have to guide the users to a correct installation, 

On my todo-list.
Note that in most cases users have nothing to do: their test and prod environment is Linux and their DPX files are supported by the FFmpeg version from their distro, so the .rpm/.deb already mandates the "right" FFmpeg version. Same for Homebrew.

**Comment by retokromer** [comment]
(I don’t remember the details, but I do remember that Peter has a very old version in his Ubuntu not so long ago.)

**Pull request merged**
