### PR TITLE
Tweaking of the computing of the count of slices

### PR DESCRIPTION
**Pull request by JeromeMartinez**
The decoder limitation is now only for DPX having more than 1 pixel in a block

### CODE REVIEW

**Comment by retokromer** [comment]
Untested, but looks good to me. Thank you!

**Comment by JeromeMartinez** [comment]
> Untested

@g-maxime is on that for the theoretical part, and @digitensions is on that for the practical part :) (she has a couple of files with weird pixel sizes).
[This snapshot is built with this PR](https://mediaarea.net/download/snapshots/binary/rawcooked/20200310/).

**Comment by retokromer** [comment]
(Remember we have to deliver 5 non-standard flavours of DPX to 5 “strange” clients… ;-)

**Comment by JeromeMartinez** [comment]
>  5 non-standard flavours of DPX 

Please provide 1 sample file of each.

**Comment by digitensions** [comment]
Thanks for getting this fixed so quickly. I'll run one of the 4 slice sequences through it today/tomorrow

**Comment by digitensions** [comment]
Cooked perfectly well, thank you. Now has MaxSlicesCount 64. Is this your new default slice figure? The pixel size for the sequence was 2444x1798.

Many thanks

**Comment by digitensions** [comment]
Guess I can be one of the strange clients :)

**Comment by JeromeMartinez** [comment]
>  Is this your new default slice figure?

The default is still same, just that I removed the reduction of the count of slices with weird pixel sies.
SD (<1440) 16 slices (10-bit) or 24 slices (16-bit)
HD/2K (>=1440, <2880) : 64 slices (10-bit) or 96 slices (16-bit)
UHD/4K (>=2880): 256 slices (10-bit) or 384 slices (16-bit)

**Pull request merged**
