### PR TITLE
Enable RGBA64 support

### PR DESCRIPTION
**Pull request by JeromeMartinez**
But FFmpeg will currently reject the command (patch for RGBA64 support in FFmpeg was sent, waiting for being accepted)

### CODE REVIEW

**Comment by retokromer** [comment]
FYI: The release 3.4.2 has just been made. I don’t know if this has been back-ported.

**Comment by JeromeMartinez** [comment]
I use nightly builds so fine.
Issue for this PR was that 1 of the RGBA64 test files has junk after image content, so I implement support of junk after image content before merging.

**Comment by JeromeMartinez** [comment]
@retokromer at long term I won't depend on FFmpeg releases, as I plan to have an internal encoder too. Using FFmpeg snapshots is an intermediary solution and will be used mainly for checking that all is in sync (that my encoder/decoder has same behavior as FFmpeg).

**Comment by retokromer** [comment]
@JeromeMartinez I know. We use our own NUT/FFV1 tool as well.

As long as you haven’t switched there is the possibility wo use a release (usually the better choice) or the HEAD. BTW 3.5 should be imminent.

**Pull request merged**
