### PR TITLE
Add GPU acceleration option

### PR DESCRIPTION
**Pull request by JeromeMartinez**
Preparation of the arrival of GPU accelerated FFV1 encoder/decoder in FFmpeg.

### CODE REVIEW

**Comment by retokromer** [comment]
Decoder or encoder?

**Comment by JeromeMartinez** [comment]
> Decoder or encoder?

Both are expected. But current FFmpeg patch proposal is only encoder for the moment, we are testing and polishing it before checking the decoder part (the developer says that most of the code is common to both so should not be long).

**Comment by retokromer** [comment]
Indeed!

I was troubled by https://github.com/MediaArea/RAWcooked/pull/448#issue-2661803857 mentioning decoder.

**Review by retokromer — APPROVED** [review]

**Comment by stephenmcconnachie** [comment]
@JeromeMartinez @retokromer is there a firm timescale for GPU encoding (then onward to decoding)? Obviously I am very interested.............

**Comment by JeromeMartinez** [comment]
@stephenmcconnachie a beta version of the encoder should be there this week. I send you an email.

**Pull request merged**
