### PR TITLE
Progress indicator improvement

### PR DESCRIPTION
**Pull request by JeromeMartinez**
In its own thread (not impacting demuxing thread), less UI updates (cursor moves less)

### CODE REVIEW

**Comment by JeromeMartinez** [comment]
Added more details during decoding:
time in file (similar to FFmpeg), decoding byte rate, speed compared to real time (similar to FFmpeg)
e.g. 
```
Time=00:01:03 (60%), 4.6 MiB/s, 2.99x realtime
```

For debate.

**Comment by kieranjol** [comment]
Awesome additions!

**Comment by JeromeMartinez** [comment]
@kieranjol @retokromer [snapshots](https://mediaarea.net/download/snapshots/binary/rawcooked/) have this feature now.

**Comment by retokromer** [comment]
Thank you very much, @JeromeMartinez! I will test later… while waiting for the results of the Swiss referendums.

**Comment by retokromer** [comment]
FYI @JeromeMartinez: It works fine on my end (on macOS 10.11.6 as well as Debian 9.4 and Ubuntu 18.04 LTS on Windows Subsystem).

**Pull request merged**
