### PR TITLE
AVI/v210/PCM/48kHz/16bit/2ch/S/LE support

### PR DESCRIPTION
**Pull request by JeromeMartinez**
Let's start with this audio support only, and not all options supported, more will come later.

Support of v210 + stereo in AVI.

### CODE REVIEW

**Comment by kieranjol** [comment]
Omggggggggg this is huge!!! Are you able to say who supported it?

**Comment by JeromeMartinez** [comment]
> Are you able to say who supported it?

Not sure yet, will post here if I can.

**Comment by lhibberdatnls** [comment]
Of course Jérôme can say who it is ;-) Really pleased that it's not just us who are excited to see it.

**Comment by kieranjol** [comment]
Wonderful news Lee! What a wonderful contribution to the global digipres community.

**Pull request merged**
