### PR TITLE
Metadata compression support

### PR DESCRIPTION
**Pull request by JeromeMartinez**
Warning: incompatible change with previous versions.
Enables compression of metadata with creation of a mask (most metadata bytes are same, that permits high compression for each frame) and zlib compression (when relevant), for file name / metadata before data / metadata after data.

With classic DPX having 2 KiB of header, RAWcooked metadata size is divided by ~20 (so for a 2-hour film, RAWcooked metadata size is shrank from ~400 MiB to ~ 20 MiB. For DPX having 64 kiB of header (mainly 0-padding), RAWcooked metadata size is divided by ~1000.

There are now typically ~100 bytes of RAWcooked metadata per video frame.
For an HD film with 2 KiB DPX header, it means that metadata is shrank from ~0.02% overhead (compared to file without RAWcooked) to ~0.001% 

Higher optimization could be done, at the price of higher complexity, e.g. by catching special case with file name / timecode being always increased by 1 (a classic case!), but I have doubt it is really useful (getting e.g. overhead from ~0.001% to ~0.0001%? hum).

todo:
- refactoring of the ugly redundant code
- using zlib from the platform when available
- more tests
- documentation of the RAWcooked format.
- add an option for not using compression, for people disliking it

### CODE REVIEW

**Comment by retokromer** [comment]
>Warning: incompatible change with previous versions.

This is not a problem at all! We are still playing with alpha…

>Higher optimization could be done, at the price of higher complexity,

In my personal opinion, the advantage of higher compression of the metadata is less than the disadvantage of higher complexity.

**Comment by kieranjol** [comment]
Will this be optional or a default?

**Comment by JeromeMartinez** [comment]
> Will this be optional or a default?

Currently the only possibility, but I can add an option (after refactoring, in few days, if you can wait).
I suggest to have the compression enabled by default.

**Comment by retokromer** [comment]
>I suggest to have the compression enabled by default.

+1

**Pull request merged**
