### PR TITLE
man: better wording

### PR DESCRIPTION
**Pull request by retokromer**
This contains part of the suggestions made by @digitensions in her [PR](https://github.com/MediaArea/RAWcooked/pull/220).

### CODE REVIEW

**Comment by retokromer** [comment]
It’s not clear to me what hurts Travis…

**Comment by JeromeMartinez** [comment]
> This contains part of the suggestions made by @digitensions in her PR.

there may be an edit conflict at some point, which one would be better to check & merge first?

**Comment by g-maxime** [comment]
Travis apply your branch to the master before build but uses the outdated .travis.xml from your branch.

Please rebase.

**Comment by retokromer** [comment]
>there may be an edit conflict at some point, which one would be better to check & merge first?

Here should be included the obvious parts. We have to discuss dome of the other parts, because I am not sure that the proposed changes are correct.

**Comment by digitensions** [comment]
Thanks for implementing the changes, and I am sure there will be a few errors. Pls notify if you need me to assist with adjustments etc.

**Comment by JeromeMartinez** [comment]
@digitensions please [review](https://github.com/MediaArea/RAWcooked/pull/229/files) changes (on the "files changed" page, click on "review changes" and select "reject" with comments if something to change or "approve" if fine).

**Comment by digitensions** [comment]
Will do Jérôme, as soon as I can this evening. Thanks for working on it :)

**Pull request merged**
