### PR TITLE
update year

### PR DESCRIPTION
**Pull request by retokromer**

### CODE REVIEW

**Comment by JeromeMartinez** [comment]
I still hope to have a release this year, so PR stalled.

**Comment by retokromer** [comment]
Should I or not add the commits for changing the three other files?

- Sourse/CLI/rawcooked.1
- License.html
- LICENSE

**Comment by JeromeMartinez** [comment]
> Should I or not add the commits for changing the three other files?

1 commit for all date related changes please.

**Comment by retokromer** [comment]
>1 commit for all date related changes please.

Okay, I’ll check if I have the right to do it.

**Comment by retokromer** [comment]
I guess, this should be merged, in order to avoid forgetting it when the next version is released.

**Pull request merged**
