### PR TITLE
fix a few typos

### PR DESCRIPTION
**Pull request by retokromer**

### CODE REVIEW

**Comment by JeromeMartinez** [comment]
Please squash commits.

**Comment by retokromer** [comment]
I messed up something. I will retry next week.

**Comment by JeromeMartinez** [comment]
Squashed version is available at https://github.com/JeromeMartinez/RAWcooked/tree/patch-1, I can not force push for replacing the PR because you closed the PR.

**Comment by retokromer** [comment]
If I didn’t mess up another thing, then https://github.com/MediaArea/RAWcooked/pull/398 should be fine.

**Pull request closed without merging**
