### PR TITLE
add `-v` for `--version`

### PR DESCRIPTION
**Pull request by retokromer**

### CODE REVIEW

**Comment by JeromeMartinez** [comment]
I was planning -v for verbose output, as in several of tools so I prefer to not use it for version which will be less used IMO.

**Comment by retokromer** [comment]
I understand. What about `-V` for `--version`?

**Comment by JeromeMartinez** [comment]
I think it is too much but if it is important for your I prefer -V over -v.

**Comment by retokromer** [comment]
OK, I’ll drop again the short version.

**Pull request merged**
