### PR TITLE
Add mac arm64 architecture

### PR DESCRIPTION
**Pull request by g-maxime**

### CODE REVIEW

**Review by retokromer — APPROVED** [review]
LGTM (Do you still keep PowerPC?)

**Comment by JeromeMartinez** [comment]
> Do you still keep PowerPC

We keep PowerPC support in our generic template because it has no cost for us, but we don't release any PowerPC version 😋 (actually absolutely no 32-bit release of this specific project).

**Comment by retokromer** [comment]
I still have PowerPC computers. It takes forever to code in FFV1 just the 57 frames in 2K, which I often use for teaching.

**Comment by kieranjol** [comment]
Wow, is that config tweak all that's needed for Apple Silicon support?

K

‪On Tue, Jan 19, 2021 at 4:38 PM ‫רטו‬‎ <notifications@github.com> wrote:‬

**Comment by JeromeMartinez** [comment]
> Wow, is that config tweak all that's needed for Apple Silicon support?

Yes, and already too much (our script could be a bit more generic).
In practice nowadays a new CPU arch should be more or less only an option to tweak, as long as there is nothing specific to an architecture (and even with that, there should a fallback to generic code in that case, and an update should be only for using new hardware features), but it is theory :).

**Pull request merged**
